spring:
  datasource:
    url: jdbc:mysql://studmysql01.fhict.local/dbi363774
#    url: jdbc:mariadb://localhost:3307/BrandFonds
    username: dbi363774
#    username: Maarten
    password: Geheim123!
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 8080