spring:
  datasource:
#    url: jdbc:mysql://studmysql01.fhict.local/dbi363774
    url: jdbc:mariadb://77.175.243.68:3307/BrandFonds
#    username: dbi363774
    username: Maarten
    password: Geheim123!
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 8080